#!/bin/bash

# if [ -z "$VPS_HEADSCALE_DATA_DIR" ]; then
#   VPS_HEADSCALE_DATA_DIR='/usr/local/headscale/data'
# fi
# if [ -z "$VPS_HEADSCALE_CACHE_DIR" ]; then
#   VPS_HEADSCALE_CACHE_DIR='/usr/local/headscale/cache'
# fi
# if [ -z "$VPS_HEADSCALE_LOG" ]; then
#   VPS_HEADSCALE_LOG='/usr/local/headscale/logs/headscale.log'
# fi

# headscale服务的pid
headscale_pid=0

cleanup() {
  # 先停止组网和sshd服务，否则headscale服务停止组网将无法退出
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'

  # 停止headscale服务
  echo 'Headscale stopping...'
  if ps -p $headscale_pid > /dev/null 2>&1; then
    kill $headscale_pid
  fi
  echo 'Headscale stopped'
}

start() {
  # 注册清理函数
  trap cleanup SIGTERM

  # 初始化
  # if [ ! -d "$VPS_HEADSCALE_DATA_DIR" ]; then
  #   install -m 755 -d "$VPS_HEADSCALE_DATA_DIR"
  # fi
  # if [ ! -f "$VPS_HEADSCALE_DATA_DIR/db.sqllite" ]; then
  #   touch "$VPS_HEADSCALE_DATA_DIR/db.sqllite"
  # fi
  # if [ ! -d "$VPS_HEADSCALE_CACHE_DIR" ]; then
  #   install -m 755 -d "$VPS_HEADSCALE_CACHE_DIR"
  # fi
  # vps_headscale_log_dir=$(dirname "$VPS_HEADSCALE_LOG")
  # if [ ! -d "$vps_headscale_log_dir" ]; then
  #   install -m 755 -d "$vps_headscale_log_dir"
  # fi

  # 启动headscale服务
  echo 'Headscale starting...'
  headscale serve >/var/log/headscale/serve.log 2>&1 &
  headscale_pid=$!

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 等待headscale服务退出
  if ps -p $headscale_pid > /dev/null 2>&1; then
    echo "Wait headscale: $headscale_pid"
    wait $headscale_pid
  fi
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
