#!/bin/bash

if [ -z "$VPS_NGINX_LOG_DIR" ]; then
  VPS_NGINX_LOG_DIR='/usr/local/nginx/logs'
fi
if [ -z "$VPS_NGINX_PID_FILE" ]; then
  VPS_NGINX_PID_FILE='/usr/local/nginx/nginx.pid'
fi

cleanup() {
  # 停止nginx服务
  echo 'Nginx stopping...'
  nginx -s stop
}

start() {
  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 初始化
  if [ ! -d "$VPS_NGINX_LOG_DIR" ]; then
    echo 'Nginx log dir not exists, create it.'
    install -m 755 -d "$VPS_NGINX_LOG_DIR"
  fi

  # 启动nginx服务
  echo 'Nginx starting...'
  nginx
  # 等待nginx服务结束
  nginx_pid=$(cat "$VPS_NGINX_PID_FILE" 2>/dev/null)
  echo "Wait nginx: $nginx_pid"
  while ps -p $nginx_pid > /dev/null 2>&1; do
    sleep 1
  done
  echo 'Nginx stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
