#!/bin/bash

kibana_pid=0

cleanup() {
  echo "Kibana stopping: $kibana_pid"
  if ps -p $kibana_pid > /dev/null 2>&1; then
    kill $kibana_pid
  fi
}

start() {
  # 修改所有者，如果存在挂载目录需要在脚本中进行修改
  chown -Rf kibana:kibana /home/kibana

  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 启动kibana
  echo 'Kibana starting...'
  su kibana /bin/bash -c "/home/kibana/kibana/bin/kibana" &
  kibana_pid=$!

  echo "Wait kibana: $kibana_pid"
  wait $kibana_pid
  echo 'Kibana stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
