#!/bin/bash

# 环境变量
# APP_REPO app仓库地址

cleanup() {
  # 停止应用
  echo 'App stopping...'
  /usr/local/app/scripts/app stop
}

start() {
  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo "Vps tailscale server starting..."
  vps-tailscale-server start
  echo "Vps tailscale server started"

  # 必须在vps-tailscale-server完成初始化后运行
  # 此时ssh密钥已正确被设置
  if [ ! -d /usr/local/app ]; then
    set -e
    # 设置GIT_SSH_COMMAND避免git clone过程中出现yes/no的ssh询问
    # export GIT_SSH_COMMAND="ssh -o \"StrictHostKeyChecking=no\""
    # clone app仓库
    echo "Git clone from $APP_REPO"
    git clone $APP_REPO /usr/local/app
    echo 'Git clone done'
    # 构建app
    echo 'App building...'
    cd /usr/local/app
    /usr/local/app/scripts/app env
    /usr/local/app/scripts/app build
    echo 'App build done'
  fi

  echo 'App starting...'
  /usr/local/app/scripts/app start
  app_pid=$(/usr/local/app/scripts/app pid)
  echo "Wait app pid: $app_pid"
  while ps -p $app_pid > /dev/null 2>&1; do
    sleep 1
  done
  echo 'App stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
