#!/bin/bash

# 环境变量
# APP_REPO app仓库地址

pull_and_build() {
  if [ ! -d /usr/local/app ]; then
    set -uex
    # 设置GIT_SSH_COMMAND避免git clone过程中出现yes/no的ssh询问
    # export GIT_SSH_COMMAND="ssh -o \"StrictHostKeyChecking=no\""
    # clone app仓库
    git clone $APP_REPO /usr/local/app
    # 构建app
    cd /usr/local/app
    /usr/local/app/scripts/app env
    /usr/local/app/scripts/app build
  fi
}

cleanup() {
  # 停止应用
  echo 'stop vps-app'
  /usr/local/app/scripts/app stop

  # 停止组网和sshd服务
  echo 'stop vps-tailscale-server'
  vps-tailscale-server stop
}

start() {
  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo "start vps-tailscale-server"
  vps-tailscale-server start

  # 必须在vps-tailscale-server完成初始化后运行
  # 此时ssh密钥已正确被设置
  pull_and_build

  echo 'start vps-app'
  /usr/local/app/scripts/app start
  app_pid=$(/usr/local/app/scripts/app pid)
  if [ -n "$app_pid" ]; then
    echo "wait app_pid: $app_pid"
    wait $app_pid
  fi
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
