#!/bin/bash

cleanup() {
  echo "Es stopping"
  es_pid=$(ps -ef | grep Elasticsearch | grep -v grep | awk '{print $2}')
  if ps -p $es_pid > /dev/null 2>&1; then
    kill $es_pid
    while ps -p $es_pid > /dev/null 2>&1; do
      sleep 1
    done
  fi
  echo 'Es stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

start() {
  # 需要特权--privileged
  sysctl -w vm.max_map_count=262144
  sysctl -w vm.swappiness=1
  sysctl -w net.core.somaxconn=2048

  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 启动es
  echo 'Es starting...'
  su - es /bin/bash -c "/home/es/es/bin/elasticsearch -d $ES_OPTS"

  es_pid=$(ps -ef | grep Elasticsearch | grep -v grep | awk '{print $2}')
  echo "Wait es: $es_pid"
  while ps -p $es_pid > /dev/null 2>&1; do
    sleep 1
  done
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
