#!/bin/bash

if [ -z "$VPS_V2RAY_LOG_DIR" ]; then
  VPS_V2RAY_LOG_DIR='/usr/local/v2ray/logs'
fi

v2ray_pid=0

cleanup() {
  # 停止v2ray服务
  echo 'V2ray stopping...'
  if ps -p $v2ray_pid > /dev/null 2>&1; then
    kill $v2ray_pid
  fi
}

start() {
  # 注册清理函数
  trap cleanup SIGTERM

  # 初始化
  if [ ! -d "$VPS_V2RAY_LOG_DIR" ]; then
    echo 'V2ray log dir not exists, create it.'
    install -m 755 -d "$VPS_V2RAY_LOG_DIR"
  fi

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 启动v2ray服务
  echo 'V2ray starting...'
  /usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json &
  v2ray_pid=$!
  # 等待v2ray服务退出
  if ps -p $v2ray_pid > /dev/null 2>&1; then
    echo "Wait v2ray: $v2ray_pid"
    wait $v2ray_pid
  fi
  echo 'V2ray stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
