#!/bin/bash

cleanup() {
  echo "Namesrv stopping"
  namesrv_pid=$(ps -ef | grep java | grep org.apache.rocketmq.namesrv.NamesrvStartup | awk '{print $2}')
  if ps -p $namesrv_pid > /dev/null 2>&1; then
    kill $namesrv_pid
    while ps -p $namesrv_pid > /dev/null 2>&1; do
      sleep 1
    done
  fi
  echo 'Namesrv stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

start() {
  # 修改所有者，如果存在挂载目录需要在脚本中进行修改
  chown -Rf rocketmq:rocketmq /home/rocketmq

  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 启动namesrv
  echo 'Namesrv starting...'
  root_env=$(xargs -0 < /proc/1/environ)
  su - rocketmq /bin/bash -c "env $root_env /home/rocketmq/rocketmq/bin/mqnamesrv" &

  # 延迟等待启动
  sleep 3

  namesrv_pid=$(ps -ef | grep java | grep org.apache.rocketmq.namesrv.NamesrvStartup | awk '{print $2}')
  echo "Wait namesrv: $namesrv_pid"
  while ps -p $namesrv_pid > /dev/null 2>&1; do
    sleep 1
  done
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
