#!/bin/bash

if [ -z "$VPS_V2RAY_LOG_DIR" ]; then
  VPS_V2RAY_LOG_DIR='/usr/local/v2ray/logs'
fi

v2ray_pid=0

cleanup() {
  echo 'cleanup vps-v2ray'

  # 停止v2ray服务
  echo 'stop v2ray'
  if ps -p $v2ray_pid > /dev/null 2>&1; then
    echo "kill v2ray: $v2ray_pid"
    kill $v2ray_pid
    wait $v2ray_pid
  fi

  # 停止组网和sshd服务
  echo 'stop vps-tailscale-server'
  vps-tailscale-server stop
}

start() {
  # 注册清理函数
  trap cleanup SIGTERM

  # 初始化
  if [ ! -d "$VPS_V2RAY_LOG_DIR" ]; then
    install -m 755 -d "$VPS_V2RAY_LOG_DIR"
  fi

  # 启动组网和sshd服务
  echo 'start vps-tailscale-server'
  vps-tailscale-server start

  # 启动v2ray服务
  echo 'start v2ray'
  /usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json &
  v2ray_pid=$!

  # 等待v2ray服务退出
  if ps -p $v2ray_pid > /dev/null 2>&1; then
    echo "wait v2ray: $v2ray_pid"
    wait $v2ray_pid
  fi
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
