#!/bin/bash

# headscale服务的pid
calibre_web_pid=0

cleanup() {
  # 停止headscale服务
  echo 'Calibre web stopping...'
  if ps -p $calibre_web_pid > /dev/null 2>&1; then
    kill $calibre_web_pid
  fi
}

start() {
  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 初始化
  if [ ! -d /usr/local/calibre-web/logs ]; then
    echo 'Calibre web log dir not exists, create it.'
    install -m 755 -d /usr/local/calibre-web/logs
  fi
  # if [ -f /usr/local/tmp/metadata.db ]; then
  #   mv /usr/local/tmp/metadata.db /usr/local/calibre-web/data/metadata.db
  # fi

  # 启动calibre-web服务
  # https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface#command-line-options
  echo 'Calibre web starting...'
  cps &
  calibre_web_pid=$!

  # 等待headscale服务退出
  if ps -p $calibre_web_pid > /dev/null 2>&1; then
    echo "Wait calibre web: $calibre_web_pid"
    wait $calibre_web_pid
  fi
  echo 'Calibre web stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
