#!/bin/bash

init() {
  if [ -d "$SSH_DOCKER_DIR" ]; then
    if [ -f "$SSH_DOCKER_DIR/authorized_keys" ] && [ ! -f /root/.ssh/authorized_keys ]; then
        install -m 600 -o root -g root "$SSH_DOCKER_DIR/authorized_keys" /root/.ssh/authorized_keys
    fi
    if [ -f "$SSH_DOCKER_DIR/id_rsa" ] && [ ! -f /root/.ssh/id_rsa ]; then
        install -m 600 -o root -g root "$SSH_DOCKER_DIR/id_rsa" /root/.ssh/id_rsa
    fi
    if [ -f "$SSH_DOCKER_DIR/authorized_keys" ] && [ ! -f /root/.ssh/id_rsa.pub ]; then
        install -m 644 -o root -g root "$SSH_DOCKER_DIR/id_rsa.pub" /root/.ssh/id_rsa.pub
    fi
  fi
}

case "$1" in
  'init')
    init
    ;;
  *)
    echo "Usage: $0 {init}"
    ;;
esac
