#!/bin/bash

cleanup() {
  echo "Rocketmq dashboard stopping"
  dashboard_pid=$(ps -ef | grep java | grep rocketmq-dashboard | grep -v su | awk '{print $2}')
  kill $dashboard_pid
}

start() {
  # 修改所有者，如果存在挂载目录需要在脚本中进行修改
  chown -Rf rocketmq:rocketmq /home/rocketmq

  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 启动namesrv
  echo 'Rocketmq dashboard starting...'
  su rocketmq /bin/bash -c "java $JAVA_OPTS -jar /home/rocketmq/rocketmq-dashboard-1.0.0.jar $SPRING_BOOT_OPTS" &

  # 延迟等待启动
  sleep 3

  dashboard_pid=$(ps -ef | grep java | grep rocketmq-dashboard | grep -wv su | awk '{print $2}')
  echo "Wait rocketmq dashboard: $dashboard_pid"
  while ps -p $dashboard_pid > /dev/null 2>&1; do
    sleep 1
  done
  echo 'Rocketmq dashboard stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
