name: build and push dockers

on:
  # 推送main触发
  push:
    branches:
      - main
  # 手动触发
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        # https://github.com/actions/checkout
        name: checkout main branch
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: setup qemu
        uses: docker/setup-qemu-action@v3
      -
        # https://github.com/docker/setup-buildx-action
        name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: build and push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          chmod +x build-and-push.sh
          ./build-and-push.sh
