#!/bin/bash

mqbin_dir='/home/rocketmq/rocketmq/bin'

cleanup() {
  echo "Broker stopping"
  $mqbin_dir/mqshutdown broker
}

start() {
  # 修改所有者，如果存在挂载目录需要在脚本中进行修改
  chown -Rf rocketmq:rocketmq /home/rocketmq

  # 注册清理函数
  trap cleanup SIGTERM

  # 启动组网和sshd服务
  echo 'Vps tailscale server starting...'
  vps-tailscale-server start
  echo 'Vps tailscale server started'

  # 启动namesrv
  echo 'Broker starting...'
  su rocketmq /bin/bash -c "$mqbin_dir/mqbroker -c $BROKER_CONF --enable-proxy" &

  # 延迟等待启动
  sleep 3

  # broker_pid=$(ps -ef | grep java | grep org.apache.rocketmq.broker.BrokerStartup | awk '{print $2}')
  # 5.x使用Proxy
  broker_pid=$(ps -ef | grep java | grep org.apache.rocketmq.proxy.ProxyStartup | awk '{print $2}')
  echo "Wait namesrv: $broker_pid"
  while ps -p $broker_pid > /dev/null 2>&1; do
    sleep 1
  done
  echo 'Broker stopped'

  # 停止组网和sshd服务
  echo 'Vps tailscale server stopping...'
  vps-tailscale-server stop
  echo 'Vps tailscale server stopped'
}

case "$1" in
  'start')
    start
    ;;
  *)
    echo "Usage: $0 {start}"
    ;;
esac
